//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IprojMigrationTool.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IprojMigrationTool.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   プロジェクト一式をバックアップ済みですか。
        ///未実施の場合はキャンセルしてバックアップしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmBackupProjectCompleted {
            get {
                return ResourceManager.GetString("ConfirmBackupProjectCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モデルファイルを分割します。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DividingModelFile {
            get {
                return ResourceManager.GetString("DividingModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移行処理できないファイルがあります。出力メッセージを確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCheckProjectFilesStatus {
            get {
                return ResourceManager.GetString("ErrorCheckProjectFilesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iprojファイルの移行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtensionIProjMigrationCommand {
            get {
                return ResourceManager.GetString("ExtensionIProjMigrationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分ロード設定の移行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtensionPartialLoadMigrationCommand {
            get {
                return ResourceManager.GetString("ExtensionPartialLoadMigrationCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iproj移行支援 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtensionRibbonGroup {
            get {
                return ResourceManager.GetString("ExtensionRibbonGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクステンション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtensionRibbonTab {
            get {
                return ResourceManager.GetString("ExtensionRibbonTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Info] 参照登録されているモデルファイルがあります。処理完了後に .nmdl ファイルに差し替えてください。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExternalModelFileInfo {
            get {
                return ResourceManager.GetString("ExternalModelFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB形式プロジェクトファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDialogIprojFilterDescription {
            get {
                return ResourceManager.GetString("FileDialogIprojFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JSON形式プロジェクトファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDialogNprojFilterDescription {
            get {
                return ResourceManager.GetString("FileDialogNprojFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのプロジェクトファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDialogProjectFilterDescription {
            get {
                return ResourceManager.GetString("FileDialogProjectFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .iproj ファイルを開いてから実行してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IprojFileNotOpened {
            get {
                return ResourceManager.GetString("IprojFileNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iprojファイルの移行を完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IprojMigrationCompletedMessage {
            get {
                return ResourceManager.GetString("IprojMigrationCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iprojファイルの移行を開始します。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IprojMigrationStartMessage {
            get {
                return ResourceManager.GetString("IprojMigrationStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   モデルファイルをロードします。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingModelFile {
            get {
                return ResourceManager.GetString("LoadingModelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この機能はまだ実装されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotImplementedMessage {
            get {
                return ResourceManager.GetString("NotImplementedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象プロジェクトは .iproj ファイルではありません。処理を終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotIprojExtension {
            get {
                return ResourceManager.GetString("NotIprojExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象プロジェクトは .nproj ファイルではありません。処理を終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotNprojExtension {
            get {
                return ResourceManager.GetString("NotNprojExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .nproj ファイルの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NprojSaveFailed {
            get {
                return ResourceManager.GetString("NprojSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Info] 構成管理ファイルの拡張子変更コマンド一覧を出力しました。これを参考に対処してください。  : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputGitSvnMvCommandsCompleted {
            get {
                return ResourceManager.GetString("OutputGitSvnMvCommandsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   構成管理ファイルの拡張子変更コマンド一覧の出力に失敗しました。: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputGitSvnMvCommandsFailed {
            get {
                return ResourceManager.GetString("OutputGitSvnMvCommandsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分ロード設定の移行を完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartialLoadMigrationCompleted {
            get {
                return ResourceManager.GetString("PartialLoadMigrationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分ロード設定の移行は Enterprise エディション用です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartialLoadMigrationEnterpriseOnly {
            get {
                return ResourceManager.GetString("PartialLoadMigrationEnterpriseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分ロード設定の移行に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartialLoadMigrationFailed {
            get {
                return ResourceManager.GetString("PartialLoadMigrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分ロード設定を移行しました。対象プロジェクトを開きます。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartialLoadMigrationOpenProject {
            get {
                return ResourceManager.GetString("PartialLoadMigrationOpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分ロード設定の移行を開始します。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartialLoadMigrationStartMessage {
            get {
                return ResourceManager.GetString("PartialLoadMigrationStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部分ロード設定が見つかりませんでした。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartialLoadNotFound {
            get {
                return ResourceManager.GetString("PartialLoadNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Info] プロファイルがファイル分割されていました。処理完了後にプロファイルをファイル分割してください。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileFileSplitInfo {
            get {
                return ResourceManager.GetString("ProfileFileSplitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Info] プロファイル名が .iprof ファイル名と異なっています。プロファイル分割の作業手順を確認ください。プロファイル名 : &quot;{0}&quot;, iprof ファイル名 : &quot;{1}&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileNameDifferenceInfo2 {
            get {
                return ResourceManager.GetString("ProfileNameDifferenceInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [Info] 参照しているプロファイルがあります。.iprof 形式の場合は .nprof 形式にアップデートしてください。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProfileReferenceInfo {
            get {
                return ResourceManager.GetString("ProfileReferenceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトをJSON形式で保存します。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SavingNproj {
            get {
                return ResourceManager.GetString("SavingNproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元ファイルの削除に失敗しました: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SourceFileDeleteFailed {
            get {
                return ResourceManager.GetString("SourceFileDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ファイルが読み取り専用です。読み取り専用を解除してください。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TargetFileIsReadonly1 {
            get {
                return ResourceManager.GetString("TargetFileIsReadonly1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ファイルが存在しません。プロジェクトを閉じてファイルを修復してください。 : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TargetFileNotExist1 {
            get {
                return ResourceManager.GetString("TargetFileNotExist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロジェクトに保存されていない変更があります。実行前に保存してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsavedProjectChanges {
            get {
                return ResourceManager.GetString("UnsavedProjectChanges", resourceCulture);
            }
        }
    }
}
